module.exports = {
  testEnvironment: 'node',
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/**/*.js',
    '!src/docs/**',
    '!src/config/index.js',
    '!src/constants/index.js',
    '!src/controllers/index.js',
    '!src/middlewares/index.js',
    '!src/middlewares/validators/index.js',
    '!src/models/index.js',
    '!src/repositories/index.js',
    '!src/routes/**',
    '!src/services/index.js',
    '!src/sockets/index.js',
    '!src/sockets/handlers/index.js',
    '!src/utils/index.js',
  ],
  testMatch: ['**/tests/**/*.test.js'],
  verbose: true,
  testTimeout: 10000,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  setupFilesAfterEnv: ['<rootDir>/src/tests/setup.js'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
}