apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: fastchat-postgres
      db: postgres
  template:
    metadata:
      labels:
        app: fastchat-postgres
        db: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:16-alpine
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi